### ISSUE TITLE
Cannot start R3 in windows 10 x64

### ISSUE THREAD

**Issue by trumpetlicks** [djipi/Virtual-Jaguar-Rx#12]
After a clean install, this is all I get.

![virtualjaguar start](https://user-images.githubusercontent.com/5900107/44658148-b2536600-a9cd-11e8-9545-cb2344b74b55.png)

This is what the install directory look like after clean install.

![image](https://user-images.githubusercontent.com/5900107/44658180-d1ea8e80-a9cd-11e8-84bf-e75b83837af6.png)

**Comment by djipi** [comment]
Sorry for this trouble. I need to investigate it.
Just in case of, could you tell me if you have a Visual Studio and/or QT installed too?

**Comment by trumpetlicks** [comment]
I DO have VS, NOT QT.  If looking for a release however, that shouldn't be a requirement :-) 

    On ‎Monday‎, ‎August‎ ‎27‎, ‎2018‎ ‎05‎:‎11‎:‎43‎ ‎PM‎ ‎EDT, Jean-Paul Mari <notifications@github.com> wrote:  
 
 
Sorry for this trouble. I need to investigate it.
Just in case of, could you tell me if you have a Visual Studio and/or QT installed too?

**Comment by djipi** [comment]
DLLs were missing and have been included in the install.
\imageformats\qjpeg.dll
\platforms\qdirect2d.dll
\platforms\qminimal.dll
\platforms\qoffscreen.dll
\platforms\qwindows.dll
