### ISSUE TITLE
Compiler error, possible Windows header in Linux Build?

### ISSUE THREAD

**Issue by Zombie-Ryushu** [djipi/Virtual-Jaguar-Rx#26]
*** Compiling src/eeprom.cpp...
src/eeprom.cpp:19:20: fatal error: direct.h: No such file or directory

**Comment by djipi** [comment]
Thank you to have try to compile in Linux. I did a work around fix for it, available in the develop branch.

**Comment by Zombie-Ryushu** [comment]
Another build error.
src/jaguar.cpp:28:23: fatal error: QMessageBox: No such file or directory
compilation terminated.

**Comment by djipi** [comment]
It seems you do not have Qt installed.
Have you configured your Linux environment to support the librairies listed?
https://github.com/djipi/Virtual-Jaguar-Rx/wiki/Librairies

**Comment by Zombie-Ryushu** [comment]
I installed QT5-devel 5.11.2 and it still failed with the same error. Is it possible to build without QT or for libretro?

**Comment by djipi** [comment]
> I installed QT5-devel 5.11.2 and it still failed with the same error. Is it possible to build without QT or for libretro?

Unfortunately, you must have Qt to compile Virtual Jaguar.
I do not recall libretro needs Qt, but feel free to give it a try.

**Comment by Zombie-Ryushu** [comment]
libretro builds successfully, but is hundreds of commits behind the main binary.

**Comment by djipi** [comment]
> libretro builds successfully, but is hundreds of commits behind the main binary.

In this case, it will be better for you to be in touch with the libretro's team.

**Comment by Zombie-Ryushu** [comment]
libqt5widgets-devel:/usr/include/qt5/QtWidgets/QMessageBox
Come to find out I do have QMessage Box installed, but VJ isn't detecting it still. Could there be a Syntax error in the include?

**Comment by djipi** [comment]
> libqt5widgets-devel:/usr/include/qt5/QtWidgets/QMessageBox
> Come to find out I do have QMessage Box installed, but VJ isn't detecting it still. Could there be a Syntax error in the include?

Visual Studio Project needs to be adapted to your directory structures both for include and library paths.
It will also be good to install the Qt Visual Studio Tools like mentioned in the wiki.

**Comment by Zombie-Ryushu** [comment]
This is a Linux Build. I don't have Visual Studio. Also, libretro needs to be an alternative makefile for the main Virtual Jaguar-RX Fork, what ibretro has is from the old Virtual Jaguar. 

My goal here is to eliminate my existing Virtual Jaguar bugs on old hardware. Some time during VJ's Development, between 2.1.0. and 2.1.1 a bug was introduced that slowed everything down.

**Comment by djipi** [comment]
Virtual Jaguar Rx version is dedicated to add a debugger and some improvements, if during the modifications I found issues in the emulator I will try to handle it but this is not my focus.

What you can do is to get the sources and do comparisons between 2.1.0 and 2.1.1.
The Rx version started with version 2.1.3.
