### ISSUE TITLE
Add Linux Friendly libretro build to this Emulator.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [djipi/Virtual-Jaguar-Rx#27]
Add Linux Friendly libretro build to Virtual Jaguar RX. This does not build under any version of Linux I throw at it however new. As such, I am requesting a Libretro section be added to this Emulator, where the current code produces a libretro module for Linux. This should not require a fork of the emulator. merely a change in Make Parameters, as other emulators do this.

**Comment by djipi** [comment]
Are you able to compile the original Virtual Jaguar on Linux?
http://icculus.org/virtualjaguar/

**Comment by Zombie-Ryushu** [comment]
Yes I can.

**Comment by Zombie-Ryushu** [comment]
I have built both the SDL/GTK/QT versions of  Virtual Jaguar along with the libretro module for a long time. But the some point between vrsion 2.1.0 and 2.1.2, some bug was introduced that caused the emulator to run at around 60% Speed on low power hardware that was never fixed.

I have some aging Intel hardware I use for Emulation. While version 2.1.0 runs at fullspeed, it has graphical and control issues, and no libretro port. the libretro port that exists is based on 2.1.2 so it has the slowdown bug.

libretro should be a build target in the main emulator. It is largely platform Agnostic Between Linux and Windows. It would allow the core emulation to be kept up to date with minimal fuss. Many emulators have an independent make -f Makefile.libretro option.

**Comment by djipi** [comment]
This has been more or less discussed with #25, #26.

The best for you will be to check the differences in the source codes between v2.1.0 and v2.1.2.
Virtual Jaguar Rx is based on Virtual Jaguar v.2.1.3. So your issue is already in Rx.

Adding a Makefile.libretro option won't be enough, it will require to transform the Rx version in a libreto form too.
But it won't fix your performance issue.

**Comment by djipi** [comment]
libreto already exists; the Rx version is dedicated to add debugging capabilities, plus potential improvements. Rx is also supporting only 64 bits (Windows).
