### ISSUE TITLE
Object List at 0

### ISSUE THREAD

**Issue by 42Bastian** [djipi/Virtual-Jaguar-Rx#51]
Object list at $0 does not work. List window shows it correct, but no display.

**Comment by djipi** [comment]
Does it occurs also on the original VJ?
Could you also provide a sample executable or source code? it can be helpful to investigate.

**Comment by 42Bastian** [comment]
2.1.2 shows the same behavior.
[mini.zip](https://github.com/djipi/Virtual-Jaguar-Rx/files/8149175/mini.zip)
Fix for PAL. Uses rln/rmac.

**Comment by 42Bastian** [comment]
Phoenix does not work either.

**Comment by djipi** [comment]
Thank you for this information, I do not promise a fix but will try to have a look at it.

**Comment by djipi** [comment]
Problem probably comes from the OPProcessList(...) function, located in the op.cpp file.
Need to check with the dev. documentation and/or to check on the console if a 0 value is "legit".

**Comment by 42Bastian** [comment]
As it works on real machines, it is kinda 'legit' ;-)

**Comment by djipi** [comment]
I've found the issue and fixed it at my side, the $0 value is used now but your example still displays a black screen.
It is possible additional problem(s) prevent this display.
Could you take a picture of your example running on console? Can be helpful to know how your example should look alike.

**Comment by 42Bastian** [comment]
The mini.j64 is made for PAL. In NTSC it does not show anything.
Attached version is for NTSC
![IMG_1129](https://user-images.githubusercontent.com/20296416/156503320-a6ddc695-b862-4cdd-b3ca-a1843538c8c1.JPG)
[mini_ntsc.zip](https://github.com/djipi/Virtual-Jaguar-Rx/files/8175241/mini_ntsc.zip)

**Comment by djipi** [comment]
I think the remaining problem(s) with mini and mini_ntsc comes from somewhere else.
The fix for the Object List at $0 allows now to display the fire256 demo (which plays very slow on the emulator).
![2022-03-03 10_12_54-Virtual Jaguar v2 1 3 Rx - Now playing_ _fire256 j64_](https://user-images.githubusercontent.com/1195657/156600608-48c0f6cb-835c-40ee-ab7d-102de8473193.jpg)

I will open a specific issue when I will know more about the mini and mini_ntsc not working.

**Comment by 42Bastian** [comment]
Ok. fire256 is also slow on real. Try gpufire256 or quickfire (both in new_bjl on githup).
mini.S uses PIT1 (sorry, did forget):
`	move.w	$38(a4),(a0)+`
Since reading PIT is not supported, it writes 0 to the screen buffer.
