### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by 42Bastian** [djipi/Virtual-Jaguar-Rx#63]
After some hassle finding and building support libraries, there are three differences/issues:

1) elf_getshdrnum(ElfMem, &NbrSect)
Though it seems to be in libelf, linker complains it is missing.

2) #include <GL/glext.h>
The latest Windows SDK does not have this file anymore.

3) I need to run windeployqt.exe and get a hell of a bunch of .dll s

My suggestions: Provide the "SDK" files (other then Qt) with the needed libraries and headers. This makes it easier for others to work on the main stuff.

Cheers

**Comment by djipi** [comment]
> After some hassle finding and building support libraries, there are three differences/issues:

The required libraries are described in the project Wiki.
https://github.com/djipi/Virtual-Jaguar-Rx/wiki/Librairies

> 3. I need to run windeployqt.exe and get a hell of a bunch of .dll s

I've never used this tool, and do not understand why it is necessary. I add the required DLLs in the emulator executable Windows package.
Some information about Qt can be found in the project Wiki.
https://github.com/djipi/Virtual-Jaguar-Rx/wiki/Librairies

> My suggestions: Provide the "SDK" files (other then Qt) with the needed libraries and headers. This makes it easier for others to work on the main stuff.

I have added the OpenGL and libelf's VS 2017 libraries in this issue.

[OpenGL.zip](https://github.com/djipi/Virtual-Jaguar-Rx/files/9111712/OpenGL.zip)
[libelf-0.8.13.zip](https://github.com/djipi/Virtual-Jaguar-Rx/files/9111718/libelf-0.8.13.zip)

**Comment by 42Bastian** [comment]
> The required libraries are described in the project Wiki.

Yes, but building them was the hassle. And the project file expects them at specific places (C:\SDK\ ...). I suggest 
a) Add a hint to the wiki
b) Make those relative to a environment variable like $(VJ_SDK)

> I've never used this tool,

I did use Qt 3.11, and only needed one .dll, now your build needs 5. But my build complains about Qt not being correctly installed. And dropping it on windeploy exe copies all these.

**Comment by 42Bastian** [comment]
Just see, your "release" has also these libraries in platforms and imageformats.
I guess the tool is "over" correct.
